global:
  scrape_interval: 15s
  evaluation_interval: 30s
#  external_labels:
#    test: 123
  
rule_files:
- "/data/prometheus_server/etc/rules.yml"


scrape_configs:
- job_name: "prometheus_server"
  scrape_interval: 30s
  scrape_timeout: 30s
  static_configs:
  - targets: ["127.0.0.1:9100"]
    labels:
      hostname: "promethues_server"
      groupname: "prometheus"


alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - "127.0.0.1:9093"

